[package]
name = "postgres-notify"
version = "0.1.0"
authors = ["projektir <oprojektir@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "=0.2.11", features = ["macros"] }
tokio-postgres = "=0.5.2"

futures = "=0.3.4"
